spring:
  application:
    name: gs-games
  datasource:
    url: jdbc:postgresql://localhost:5432/games
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

server:
  port: 7102

