export const LOAD_PLAYERS = 'LOAD_AUTHORS'
export const LOAD_GAMES = 'LOAD_GAMES'
export const LOAD_TEAMS = 'LOAD_TEAMS'
export const LOAD_GAME_SESSIONS = 'LOAD_GAME_SESSIONS'
// export const LOAD_COMMENTS = 'LOAD_COMMENTS'

export const ADD_GAME = 'ADD_GAME'
export const UPDATE_GAME = 'UPDATE_GAME'
export const DELETE_GAME = 'DELETE_GAME'

export const ADD_PLAYER = 'ADD_AUTHOR'
export const UPDATE_PLAYER = 'UPDATE_AUTHOR'
export const DELETE_PLAYER = 'DELETE_AUTHOR'

export const ADD_TEAM = 'ADD_TEAM'
// export const UPDATE_TEAM = 'UPDATE_TEAM'
export const DELETE_TEAM = 'DELETE_TEAM'

export const ADD_GAME_SESSION = 'ADD_GAME_SESSION'
export const UPDATE_GAME_SESSION = 'UPDATE_GAME_SESSION'
export const DELETE_GAME_SESSION = 'DELETE_GAME_SESSION'

export const STATISTICS_PLAYER = 'STATISTICS_PLAYER'
export const STATISTICS_SESSION_MONTH = 'STATISTICS_SESSION_MONTH'

export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE'
export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE'

export const SHOW_LOGIN_DIALOG = 'SHOW_LOGIN_DIALOG'
export const CLEAR_DATA = 'CLEAR_DATA'

